package com.apiposture.cli.output;

import com.apiposture.core.models.*;

import java.time.format.DateTimeFormatter;
import java.util.Map;

/**
 * Markdown output formatter for reports and PRs.
 */
public class MarkdownFormatter implements OutputFormatter {

    @Override
    public String format(ScanResult result) {
        StringBuilder sb = new StringBuilder();

        // Title
        sb.append("# ApiPosture Security Scan Report\n\n");

        // Summary section
        sb.append("## Summary\n\n");
        sb.append("| Metric | Value |\n");
        sb.append("|--------|-------|\n");
        sb.append("| Project | `").append(result.projectPath()).append("` |\n");
        sb.append("| Files Scanned | ").append(result.scannedFiles()).append(" |\n");
        sb.append("| Scan Duration | ").append(formatDuration(result.scanDuration().toMillis())).append(" |\n");
        sb.append("| Timestamp | ").append(DateTimeFormatter.ISO_INSTANT.format(result.timestamp())).append(" |\n");
        sb.append("| Total Endpoints | ").append(result.getTotalEndpoints()).append(" |\n");
        sb.append("| Total Findings | ").append(result.getTotalFindings()).append(" |\n\n");

        // Severity breakdown
        if (result.getTotalFindings() > 0) {
            sb.append("### Findings by Severity\n\n");
            sb.append("| Severity | Count |\n");
            sb.append("|----------|-------|\n");
            Map<Severity, Integer> counts = result.getSeverityCounts();
            for (Severity severity : new Severity[]{
                    Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO}) {
                int count = counts.getOrDefault(severity, 0);
                if (count > 0) {
                    sb.append("| ").append(formatSeverityBadge(severity)).append(" | ").append(count).append(" |\n");
                }
            }
            sb.append("\n");
        }

        // Endpoints section
        if (!result.endpoints().isEmpty()) {
            sb.append("## Endpoints\n\n");

            // Group by classification
            Map<SecurityClassification, java.util.List<Endpoint>> byClass = result.getEndpointsByClassification();

            for (SecurityClassification classification : SecurityClassification.values()) {
                java.util.List<Endpoint> endpoints = byClass.get(classification);
                if (endpoints == null || endpoints.isEmpty()) continue;

                sb.append("### ").append(formatClassificationTitle(classification))
                        .append(" (").append(endpoints.size()).append(")\n\n");

                sb.append("| Method | Route | Controller | Location |\n");
                sb.append("|--------|-------|------------|----------|\n");

                for (Endpoint endpoint : endpoints) {
                    sb.append("| `").append(endpoint.formatMethods()).append("` ");
                    sb.append("| `").append(endpoint.route()).append("` ");
                    sb.append("| ").append(endpoint.controllerName()).append(".").append(endpoint.methodName()).append("() ");
                    sb.append("| ").append(formatLocation(endpoint.location())).append(" |\n");
                }
                sb.append("\n");
            }
        }

        // Findings section
        if (!result.findings().isEmpty()) {
            sb.append("## Findings\n\n");

            for (Finding finding : result.findings()) {
                sb.append(formatFinding(finding));
            }
        }

        // Footer
        sb.append("---\n\n");
        sb.append("*Generated by [ApiPosture](https://github.com/BlagoCuljak/ApiPosture.Java)*\n");

        return sb.toString();
    }

    private String formatFinding(Finding finding) {
        StringBuilder sb = new StringBuilder();

        // Header with severity badge
        sb.append("### ").append(formatSeverityBadge(finding.severity()));
        sb.append(" [").append(finding.ruleId()).append("] ").append(finding.ruleName()).append("\n\n");

        // Message
        sb.append("> ").append(finding.message()).append("\n\n");

        // Details
        if (finding.endpoint() != null) {
            sb.append("**Endpoint:** `").append(finding.endpoint().formatMethods())
                    .append(" ").append(finding.endpoint().route()).append("`\n\n");

            if (finding.endpoint().location() != null) {
                sb.append("**Location:** ").append(formatLocation(finding.endpoint().location())).append("\n\n");
            }
        }

        // Recommendation
        if (finding.recommendation() != null) {
            sb.append("**Recommendation:** ").append(finding.recommendation()).append("\n\n");
        }

        sb.append("---\n\n");
        return sb.toString();
    }

    private String formatSeverityBadge(Severity severity) {
        return switch (severity) {
            case CRITICAL -> ":red_circle: **CRITICAL**";
            case HIGH -> ":orange_circle: **HIGH**";
            case MEDIUM -> ":yellow_circle: **MEDIUM**";
            case LOW -> ":large_blue_circle: **LOW**";
            case INFO -> ":white_circle: INFO";
        };
    }

    private String formatClassificationTitle(SecurityClassification classification) {
        return switch (classification) {
            case PUBLIC -> ":unlock: Public";
            case AUTHENTICATED -> ":closed_lock_with_key: Authenticated";
            case ROLE_RESTRICTED -> ":lock: Role Restricted";
            case POLICY_RESTRICTED -> ":shield: Policy Restricted";
        };
    }

    private String formatLocation(SourceLocation location) {
        if (location == null) {
            return "unknown";
        }
        return "`" + location.filePath() + ":" + location.lineNumber() + "`";
    }

    private String formatDuration(long millis) {
        if (millis < 1000) {
            return millis + "ms";
        }
        return String.format("%.2fs", millis / 1000.0);
    }
}
